### PR TITLE
changes to details card styling and search icon animation

### PR DESCRIPTION
**Pull request by pcsandford**
@mmeiers please review. 
Changes to the detail card include:
- fixing card in center for any height and aligning to half-way under the search icon
- changing header to min-size and auto with padding to adjust to longer names
- adding in font weight 300 for Open Sans
- using :before for the underline effects
- adding div to contain degree text
- fixing height and padding of logo area so it will stay same size with one, two or three logos
- changing icon size, width and alignment, switching to div to remove a tag highlight effect
- moving script tags to top head for jquery and icon functionality - changing function to fire on button click (might need to change to jquery ui for touch effect to register)

@stulees @donnapep FYI

Thanks!

### CODE REVIEW

**Comment by mmeiers** [comment]
:+1:  Looks good, spacing and icon animation look great . @pcsandford  Could you change your indenting to 2 spaces vs 4? Sublime should have an option for that. The UX team standardized on doing that so I think we should do that as well.

**Comment by pcsandford** [comment]
@mmeiers in the last commit I have made the icon a permanent X and commented out the functionality and the extra animation code for now. If this can't be automatically merged after your commit I will do a rebase. Running a quick errand first thing this morning but will be back around 10:30. Thanks!

**Comment by mmeiers** [comment]
:+1:  Good was about to ask about the X, thanks!

**Comment by pcsandford** [comment]
@mmeiers please review. Added in the Benton Sans font in .woff format and removed reference to Open Sans in head.

**Comment by pcsandford** [comment]
@mmeiers please review. I think I have rebased correctly and so my PR now includes the changes I made as well as reflecting the changes you made such as adding images and new .html files etc. Do you want to have a quick scan through and check I haven't deleted anything by accident then I will merge this. Thanks!

**Comment by mmeiers** [comment]
:+1:

**Pull request merged**
