### PR TITLE
president's list changes

### PR DESCRIPTION
**Pull request by mmeiers**
@stulees 

Here are the presidents list changes:

CSS Changes:
I added two new classes. One called ".back-drop" the other is "img .list-area". I also changed a few z-indexes and made the footer the same height as the header.

HTML:
index.html is the first screen (reference this one to see what I changed). There are also 5 other html pages so you can see the correct image links and tab indexes.

Each screen is comprised of 3 images. 1 for the header, 1 for behind the list and 1 for the footer.

I made the header 1 composite image so we can update quicker and commented out the individual logos because the client is still unsure what they want here.

Each image is an img tag nested within their respective container tags within the html.

Let me know if you have any questions.

### CODE REVIEW

**Comment by mmeiers** [comment]
Here is a link to the gh-pages bracnh so you can preview the staged version:
http://rise-vision.github.io/UX-client-donor-wall/src/index-screen2.html
I view it dev console at 1080x1920

fyi @pcsandford @donnapep @stulees

**Comment by stulees** [comment]
@mmeiers :+1: Okay thanks. For now I will look to just update using screen 1. Implementing other screens will need to happen after I get through the detail card work.

**Comment by mmeiers** [comment]
@stulees Yep agreed, get 1 exactly how we want it then it will be easy to just copy and paste and update image links and tab indexes.

**Comment by pcsandford** [comment]
@mmeiers looks good :+1: I must have missed this PR somehow before I pushed mine so if you want to merge it I will rebase from master and then push my detail card changes again. Thanks!

**Pull request merged**
