### PR TITLE
graphic changes v2

### PR DESCRIPTION
**Pull request by mmeiers**
@stulees @pcsandford 

I have updated the graphics per client requests and also renamed the displays to account for "screen 4" which Grant is building.

I can manually merge all these changes to the client repo later. @stulees Let me know when a good time to do this would be as I imagine we would want to wait until after you are done with your current work as it involves duplicating the index html file.

I had already started this pr prior to our retro but from here on out I will be working from the client repo to make ux changes.

Thanks,
Mat

### CODE REVIEW

**Comment by pcsandford** [comment]
@mmeiers thanks, sounds good! I think that 'investments' has a typo with an extra 'e'?

**Comment by mmeiers** [comment]
@pcsandford good catch! Fixed.

**Comment by pcsandford** [comment]
@mmeiers cool, everything else looks good!

**Comment by stulees** [comment]
@mmeiers Looks good :+1:

**Pull request merged**
